apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
#kubectl apply -f local-pvc.yaml
#kubectl create secret generic mssql --from-literal=SA_PASSWORD="byksqlpa55!"
#leaving it here 'cause it's just tutorial part